version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: orders
      PGUSER: postgres
    ports:
      - "2345:2345"
    command: -p 2345
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
    - orders-volume:/var/lib/postgresql/data
  db_test:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: orders-test
      PGUSER: postgres
    ports:
      - "2346:2346"
    command: -p 2346
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - orders-test-volume:/var/lib/postgresql/data
  rust-app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      db_test:
        condition: service_healthy
      db:
        condition: service_healthy
    ports:
      - "8085:8085"
volumes:
  orders-volume:
  orders-test-volume: